-- MonsterDatabase: 20 monsters across 5 attributes (Fire/Water/Grass/Light/Dark)
return {
	-- ========== FIRE ==========
	{
		id = "flame_bunny",
		name = "ほのおウサギ",
		nameEN = "FlameBunny",
		attribute = "Fire",
		rarity = "Normal",
		baseValue = 50,
		description = "耳の先から小さな炎が出ているかわいいウサギ。",
		spawnCondition = {
			weather = "Sunny",
		},
	},
	{
		id = "magma_turtle",
		name = "マグマガメ",
		nameEN = "MagmaTurtle",
		attribute = "Fire",
		rarity = "Rare",
		baseValue = 300,
		description = "甲羅がマグマでできた頑丈なカメ。",
		spawnCondition = {
			weather = "Sunny",
			season = "Summer",
		},
	},
	{
		id = "inferno_fox",
		name = "インフェルノフォックス",
		nameEN = "InfernoFox",
		attribute = "Fire",
		rarity = "Epic",
		baseValue = 1200,
		description = "炎を操る九尾のキツネ。その尾は九本の炎でできている。",
		spawnCondition = {
			weather = "Sunny",
			season = "Summer",
			soilType = "Magic",
		},
	},
	{
		id = "phoenix_chick",
		name = "フェニックスのヒナ",
		nameEN = "PhoenixChick",
		attribute = "Fire",
		rarity = "Legend",
		baseValue = 8000,
		description = "伝説の不死鳥の幼鳥。その体は常に炎に包まれている。",
		spawnCondition = {
			weather = "Sunny",
			season = "Summer",
			soilType = "Golden",
			timeOfDay = "Noon",
		},
	},

	-- ========== WATER ==========
	{
		id = "bubble_fish",
		name = "バブルフィッシュ",
		nameEN = "BubbleFish",
		attribute = "Water",
		rarity = "Normal",
		baseValue = 50,
		description = "泡をプカプカ飛ばしながら泳ぐ小魚。",
		spawnCondition = {
			weather = "Rainy",
		},
	},
	{
		id = "rain_slime",
		name = "レインスライム",
		nameEN = "RainSlime",
		attribute = "Water",
		rarity = "Normal",
		baseValue = 60,
		description = "雨粒が集まってできたとろとろのスライム。",
		spawnCondition = {
			weather = "Rainy",
		},
	},
	{
		id = "tidal_seahorse",
		name = "タイダルタツノオトシゴ",
		nameEN = "TidalSeahorse",
		attribute = "Water",
		rarity = "Rare",
		baseValue = 320,
		description = "潮の流れを操ることができる神秘的なタツノオトシゴ。",
		spawnCondition = {
			weather = "Rainy",
			season = "Autumn",
		},
	},
	{
		id = "frost_whale",
		name = "フロストクジラ",
		nameEN = "FrostWhale",
		attribute = "Water",
		rarity = "Epic",
		baseValue = 1500,
		description = "氷の海を泳ぐ巨大なクジラ。その歌声は雪を降らせる。",
		spawnCondition = {
			weather = "Snowy",
			season = "Winter",
			soilType = "Magic",
		},
	},

	-- ========== GRASS ==========
	{
		id = "leaf_cat",
		name = "リーフキャット",
		nameEN = "LeafCat",
		attribute = "Grass",
		rarity = "Normal",
		baseValue = 55,
		description = "体中に若葉が生えているのんびり屋のネコ。",
		spawnCondition = {
			season = "Spring",
		},
	},
	{
		id = "moss_bear",
		name = "モスベア",
		nameEN = "MossBear",
		attribute = "Grass",
		rarity = "Rare",
		baseValue = 280,
		description = "全身が苔に覆われた穏やかなクマ。古い森の守り神。",
		spawnCondition = {
			season = "Spring",
			weather = "Rainy",
		},
	},
	{
		id = "bloom_deer",
		name = "ブルームディア",
		nameEN = "BloomDeer",
		attribute = "Grass",
		rarity = "Epic",
		baseValue = 1300,
		description = "角に花が咲き乱れる美しいシカ。触れると花が咲く。",
		spawnCondition = {
			season = "Spring",
			weather = "Sunny",
			soilType = "Magic",
		},
	},
	{
		id = "ancient_treent",
		name = "エンシェントトレント",
		nameEN = "AncientTreent",
		attribute = "Grass",
		rarity = "Legend",
		baseValue = 9000,
		description = "数千年生きた古代の木の精霊。その体は巨大な樹木そのものだ。",
		spawnCondition = {
			season = "Spring",
			weather = "Rainy",
			soilType = "Golden",
			timeOfDay = "Dawn",
		},
	},

	-- ========== LIGHT ==========
	{
		id = "sun_bird",
		name = "サンバード",
		nameEN = "SunBird",
		attribute = "Light",
		rarity = "Normal",
		baseValue = 80,
		description = "太陽の光を浴びて輝く小鳥。その羽ばたきは光の粒を散らす。",
		spawnCondition = {
			weather = "Rainbow",
		},
	},
	{
		id = "star_fox",
		name = "スターフォックス",
		nameEN = "StarFox",
		attribute = "Light",
		rarity = "Rare",
		baseValue = 400,
		description = "星の光を体に宿すキツネ。夜空の星のように輝く。",
		spawnCondition = {
			weather = "Rainbow",
			timeOfDay = "Night",
		},
	},
	{
		id = "holy_unicorn",
		name = "ホーリーユニコーン",
		nameEN = "HolyUnicorn",
		attribute = "Light",
		rarity = "Legend",
		baseValue = 10000,
		description = "神聖な光に包まれた伝説のユニコーン。その角は奇跡を起こす。",
		spawnCondition = {
			weather = "Rainbow",
			season = "Spring",
			soilType = "Golden",
		},
	},
	{
		id = "celestial_dragon",
		name = "セレスティアルドラゴン",
		nameEN = "CelestialDragon",
		attribute = "Light",
		rarity = "Mythic",
		baseValue = 50000,
		description = "天界から舞い降りた神話の龍。出会えた者には無限の幸運が訪れると言われる。",
		spawnCondition = {
			weather = "Rainbow",
			season = "Spring",
			soilType = "Golden",
			timeOfDay = "Noon",
			specialEvent = true,
		},
	},

	-- ========== DARK ==========
	{
		id = "shadow_wolf",
		name = "シャドウウルフ",
		nameEN = "ShadowWolf",
		attribute = "Dark",
		rarity = "Normal",
		baseValue = 70,
		description = "闇に潜む影のオオカミ。その足音は誰にも聞こえない。",
		spawnCondition = {
			timeOfDay = "Night",
		},
	},
	{
		id = "moon_owl",
		name = "ムーンアウル",
		nameEN = "MoonOwl",
		attribute = "Dark",
		rarity = "Rare",
		baseValue = 350,
		description = "月光を浴びて力を増すフクロウ。満月の夜に最も強くなる。",
		spawnCondition = {
			timeOfDay = "Night",
			weather = "Stormy",
		},
	},
	{
		id = "void_cat",
		name = "ヴォイドキャット",
		nameEN = "VoidCat",
		attribute = "Dark",
		rarity = "Epic",
		baseValue = 1800,
		description = "虚空から現れる謎多き黒猫。その目は宇宙の深淵を映す。",
		spawnCondition = {
			timeOfDay = "Night",
			weather = "Stormy",
			soilType = "Magic",
		},
	},
	{
		id = "abyssal_serpent",
		name = "アビサルサーペント",
		nameEN = "AbyssalSerpent",
		attribute = "Dark",
		rarity = "Legend",
		baseValue = 12000,
		description = "深淵から這い出た伝説の大蛇。その存在は世界の均衡を揺るがす。",
		spawnCondition = {
			timeOfDay = "Night",
			weather = "Stormy",
			season = "Winter",
			soilType = "Golden",
		},
	},
}
