-- SeedDatabase: 7 seed types with attribute, rarity, cost, and possible monsters
return {
	{
		id = "fire_seed",
		name = "ほのおのタネ",
		nameEN = "FireSeed",
		attribute = "Fire",
		rarity = "Normal",
		cost = 100,
		currencyType = "coins",
		possibleMonsters = { "flame_bunny", "magma_turtle", "inferno_fox", "phoenix_chick" },
	},
	{
		id = "water_seed",
		name = "みずのタネ",
		nameEN = "WaterSeed",
		attribute = "Water",
		rarity = "Normal",
		cost = 100,
		currencyType = "coins",
		possibleMonsters = { "bubble_fish", "rain_slime", "tidal_seahorse", "frost_whale" },
	},
	{
		id = "grass_seed",
		name = "くさのタネ",
		nameEN = "GrassSeed",
		attribute = "Grass",
		rarity = "Normal",
		cost = 100,
		currencyType = "coins",
		possibleMonsters = { "leaf_cat", "moss_bear", "bloom_deer", "ancient_treent" },
	},
	{
		id = "light_seed",
		name = "ひかりのタネ",
		nameEN = "LightSeed",
		attribute = "Light",
		rarity = "Rare",
		cost = 500,
		currencyType = "coins",
		possibleMonsters = { "sun_bird", "star_fox", "holy_unicorn", "celestial_dragon" },
	},
	{
		id = "dark_seed",
		name = "やみのタネ",
		nameEN = "DarkSeed",
		attribute = "Dark",
		rarity = "Rare",
		cost = 500,
		currencyType = "coins",
		possibleMonsters = { "shadow_wolf", "moon_owl", "void_cat", "abyssal_serpent" },
	},
	{
		id = "rainbow_seed",
		name = "にじのタネ",
		nameEN = "RainbowSeed",
		attribute = "All",
		rarity = "Epic",
		cost = 2000,
		currencyType = "coins",
		possibleMonsters = {
			"flame_bunny",
			"magma_turtle",
			"inferno_fox",
			"bubble_fish",
			"rain_slime",
			"tidal_seahorse",
			"leaf_cat",
			"moss_bear",
			"bloom_deer",
			"sun_bird",
			"star_fox",
			"shadow_wolf",
			"moon_owl",
		},
	},
	{
		id = "mystic_seed",
		name = "ミスティックシード",
		nameEN = "MysticSeed",
		attribute = "All",
		rarity = "Legend",
		cost = 80,
		currencyType = "robux",
		possibleMonsters = {
			"phoenix_chick",
			"frost_whale",
			"ancient_treent",
			"holy_unicorn",
			"celestial_dragon",
			"abyssal_serpent",
		},
	},
}
